version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "leonidboykov"
    target-branch: "source"
  - package-ecosystem: "github-actions"
    directory: "/"
    shedule:
      interval: "daily"
