language: python
python: 2.7

branches:
  only:
    - source

# before_install:
#   - git config --global user.name "${GIT_NAME}"
#   - git config --global user.email "${GIT_EMAIL}"

install:
  - pip install -r requirements.txt

# before_script:
#   - git clone --depth 1 https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git --branch ${TARGET_BRANCH} --single-branch site
#   - cd site && git rm -rf . && cd ..

script:
  - mkdocs build --clean

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: site
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: source

# env:
#   global:
  # - GIT_NAME: "Travis CI"
  # - GITHUB_USER: robotuts
  # - GITHUB_REPO: robotuts.github.io
  # - TARGET_BRANCH: master
