language: python
python: 2.7

branches:
  only:
    - source

install:
  - pip install -r requirements.txt

script:
  - mkdocs build --clean

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  target-branch: master
  local-dir: site
  on:
    branch: source
