language: python
python: 2.7

branches:
  only:
    - source

install:
  - pip install -r requirements.txt

script:
  - mkdocs build --clean

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  target_branch: master
  local_dir: site
  on:
    branch: source
