language: go
go: 1.7

branches:
  only:
  - source

before_install:
- git config --global user.name "${GIT_NAME}"
- git config --global user.email "${GIT_EMAIL}"

install:
- go get -u -v github.com/spf13/hugo

script:
- git clone https://github.com/digitalcraftsman/hugo-material-docs.git themes/hugo-material-docs
- hugo

after_success:
- cd public
- git init
- git remote add origin https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git
- touch .nojekyll
- git add -A
- git commit -m "Generated Hugo Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push -f "https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}.git" ${TARGET_BRANCH}

env:
  global:
  - GIT_NAME: "Travis CI"
  - GITHUB_USER: robotuts
  - GITHUB_REPO: robotuts.github.io
  - TARGET_BRANCH: master
