language: python
python: 3.6

branches:
  only:
  - source

before_install:
- git config --global user.name "${GIT_NAME}"
- git config --global user.email "${GIT_EMAIL}"

install:
- make install

before_script:
- git clone --depth 1 https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git --branch ${TARGET_BRANCH} --single-branch site
- cd site && git rm -rf . && cd ..

script:
- make build

after_success:
- cd site
- git add --all
- git commit -m "Generated MkDocs Site by Travis CI [Build#${TRAVIS_BUILD_NUMBER}]"
- git push --quiet "https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}.git" ${TARGET_BRANCH}

env:
  global:
  - GIT_NAME: "Travis CI"
  - GITHUB_USER: robotuts
  - GITHUB_REPO: robotuts.github.io
  - TARGET_BRANCH: master
