language: python
python: 2.7


branches:
  only:
  - source

before_install:
- git config --global user.name "${GIT_NAME}"
- git config --global user.email "${GIT_EMAIL}"

install:
- pip install -q -r requirements.txt

before_script:
- git clone --depth 1 https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git --branch ${TARGET_BRANCH} --single-branch site
- cd site && git rm -rf . && cd ..

script:
- mkdocs build

after_success:
- cd site
- git init
- git remote add origin https://github.com/${GITHUB_USER}/${GITHUB_REPO}.git
- touch .nojekyll
- git add -A
- git commit -m "Generated MkDocs Site by Travis CI [Build#${TRAVIS_BUILD_NUMBER}]"
- git push -f "https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${GITHUB_REPO}.git" ${TARGET_BRANCH}

env:
  global:
  - GIT_NAME: "Travis CI"
  - GITHUB_USER: robotuts
  - GITHUB_REPO: robotuts.github.io
  - TARGET_BRANCH: master
