baseurl = "https://robotuts.github.io/"
languageCode = "ru-ru"
title = "RoboTuts"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-73333143-1"

[params]
	# General information
	author = "RoboTuts"
	description = "-"
	copyright = "RoboTuts Docs"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/robotuts/robotuts.github.io"

	version = "0.1.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "robotuts"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true


# Navigation
[[menu.main]]
  name   = "Главная"
  url    = "/"
  weight = 0

[[menu.main]]
  name   = "Работа с Vagrant"
  url    = "vagrant/"
  weight = 10

[[menu.main]]
  name   = "Установка SDK"
  url    = "installing/"
  weight = 20
