backend:
  name: github
  repo: robotuts/robotuts.github.io
  branch: source

public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
